name: Unzip and Commit

# Give the workflow permission to write to the repository
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository with your PAT
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # Step 2: Unzip your file
      - name: Unzip anslayerV1.5.5.zip
        run: |
          mkdir -p unzipped
          unzip -o anslayerV1.5.5.zip -d unzipped

      # Step 3: Commit and push
      - name: Commit and push unzipped files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add unzipped/
          git diff-index --quiet HEAD || git commit -m "Add unzipped files"
          git push
